# -*- dockerfile -*-
FROM rockylinux:8

RUN yum install -y make git sudo epel-release yum-utils rpm-build rpmdevtools && \
    yum install -y python2 python2-pip python2-rpm-macros python2-setuptools && \
    yum clean all

RUN useradd builder -u 1000 -m -G users,wheel && \
    echo "builder ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    chown -R builder /home/builder
USER builder

ENV FLAVOR=rpmbuild OS=centos DIST=el8
CMD /srv/pkg
